### ISSUE TITLE
Feature: Idiot-proof the install location: add an option to create directory for you.

### ISSUE THREAD

**Issue by SpencerAP** [photoshelter/generator-polymer-init-element-scaffold#10]
Generator assumes you’ve already made a new directory and CD’d into it; documentation lacks these details.

**Comment by SpencerAP** [comment]
RTFM #fail

"Create your element in the folder you want to add it to."

That said, I may not be the only person who misses this. I'll change this to a feature request: generator alerts you of this behavior. Something along the lines of:

"New element will be generated in the current folder."

or

"New element will be generated in {NAME-OF-CURRENT-FOLDER}."

**Comment by oneezy** [comment]
@caranicas Would it be a good idea to generate this top level folder w/ all the contents in it? 

I too had read past this in the documentation and had 18 files spread across my desktop 😁 

-----

But my main reason being, this folder should be named the same as the element also. I see this as a small  enhancement that will save another step in the workflow.

**Comment by caranicas** [comment]
@oneezy Thanks for your interest, I have begun to think about that, potentially as an option in the generator (it is tough trying to balance utility vs. over burdening people with choices and options). 

My original philosophy was 1 component 1 repo. My flow for creating a new component had been to create a new repo, clone it, cd into the folder, and then generate my element. For creating an `internal` element, I always created a top level folder as well. The component tries to infer its name from the folder it is in, so this is why I made this choice. 

I am fairly insistent on the idea that the component should live in it's own folder, but I don't see any reason why there can't also be an option to create the folder for you first. Just an initial question "Should I create a directory for you?"  If you would like to offer a PR that would be greatly appreciated.

**Comment by oneezy** [comment]
> My flow for creating a new component had been to create a new repo, clone it, cd into the folder, and then generate my element.

Come to think of it, that's exactly what I do _(haha)_. The only time I'm not doing that is when I'm quickly testing something out or trying to introduce someone to the Polymer/ Web Components workflow.

-----

It seems like the `internal` option would be more of a candidate for this. I can imagine the scenario where I might forget to create a new folder in the project and then :boom: **BOOM!** :boom: _(Spend time on cleanup)_.

I like the idea of having that question in the generator. What do you think about having the 
**_"Create new directory?"_** default to either `No` or `Yes` depending on the users choice of either
`bower` or `internal` ?

### Choosing `bower` _(defaults to `No`)_

```
? Is this a bower element or internal element? bower
? Should I create a directory for you? (y/N)
```

### Choosing `internal` _(defaults to `Yes`)_

```
? Is this a bower element or internal element? internal
? Should I create a directory for you? (Y/n)
```

I'd be happy to submit over a PR and help contribute. I've been spending lots of time this past month on a solid approach to an element workflow also. Creating the generator was my next step, though it seems like you've made some great efforts in this area already.

**Comment by caranicas** [comment]
@oneezy sounds great. ill happily accept that.

**Comment by oneezy** [comment]
@caranicas 

I made some headway on the `polymer 1.x` version for this feature, but I'm trying to resolve some issues before I implement the `2.0` and `vanilla` versions, along with submitting over a PR.

**You can see my progress here:** [oneezy/generator-polymer-init-element-scaffold](https://github.com/oneezy/generator-polymer-init-element-scaffold)

-----

I broke down [one of the issues](http://stackoverflow.com/questions/41366469/stop-yeoman-generator-from-deleting-certain-files-and-folders) I'm having on Stack Overflow if you'd like to have a look..but here's the **TLDR**:

### Current Issues
- :x: Selecting `internal` + `directory` will add directory, but overwrite existing components
- :x: Selecting `bower` + `directory` will add files to directory, but also add components to sub-directory

### Expected Behavior
- :grey_question: Selecting `internal` + `directory` _should*_ add directory along existing components _(not overwrite)_
- :grey_question: Selecting `bower` + `directory` _should*_ add all files to new directory _(not create sub-directory)_

-----

### Tasks Completed
- :white_check_mark: Polymer 1.x Version: `createDirectory` confirm prompt added based on `bower` or `internal` choice
- :white_check_mark: Vanilla Version: fixed function typo `_VanillaOneWrite` to `_VanillaWrite`
- :white_check_mark: Code clean-up and commenting for easy navigation

### To Do
- :black_square_button: Polymer 1.x: Fix current issues
- :black_square_button: Polymer 2.0: Implementation
- :black_square_button: Vanilla Web Components: Implemenation

**Comment by oneezy** [comment]
@caranicas 

I made some headway on the `polymer 1.x` version for this feature, but I'm trying to resolve some issues before I implement the `2.0` and `vanilla` versions, along with submitting over a PR.

**You can see my progress here:** [oneezy/generator-polymer-init-element-scaffold](https://github.com/oneezy/generator-polymer-init-element-scaffold)

-----

I broke down [one of the issues](http://stackoverflow.com/questions/41366469/stop-yeoman-generator-from-deleting-certain-files-and-folders) on Stack Overflow if you'd like to have a look,
but here's the **TLDR**:

### Current Issues
- :x: Selecting `internal` + `directory` will add directory, but overwrite existing components [(see video)](https://drive.google.com/file/d/0ByR1kQvOUDJbZ1N3WGJldDExQ1k/view)
- :x: Selecting `bower` + `directory` will add files to directory, but also add components to sub-directory

### Expected Behavior
- :grey_question: Selecting `internal` + `directory` _should*_ add directory along existing components _(not overwrite)_
- :grey_question: Selecting `bower` + `directory` _should*_ add all files to new directory _(not create sub-directory)_

-----

### Tasks Completed
- :white_check_mark: Polymer 1.x Version: `createDirectory` confirm prompt added based on `bower` or `internal` choice
- :white_check_mark: Vanilla Version: fixed function typo `_VanillaOneWrite` to `_VanillaWrite`
- :white_check_mark: Code clean-up and commenting for easy navigation

### To Do
- :black_square_button: Polymer 1.x: Fix current issues
- :black_square_button: Polymer 2.0: Implementation
- :black_square_button: Vanilla Web Components: Implemenation

**Comment by caranicas** [comment]
@oneezy offer it as a PR, so I can check it out. my guess is that is has something to do with the postinstall script and how it is gated. `{<% if (elementImplementation === 'internal') { %>
    "postinstall":"ls | grep -v <%=elementName%> | xargs rm -rf"<% } else { %>`

**Comment by oneezy** [comment]
@caranicas 

I think there's a **much** smarter way I could have written this PR, relating to the `destinationPath` and `destinationRoot` _(I'm fairly new to writing custom yeoman generators)_. I'm sure it could be refactored with much less code.
